name: Build and Test React Application
on: push
jobs:
  build_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Build and run tests
        run: |
          npm ci
          npm run build --if-present
          npm test  
